"""Project configuration — SAP HANA DB ITGC tool."""
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DOMAIN = "HANA_DB"

SLOT_KEYS = [
    "USERS",
    "M_PASSWORD_POLICY",
    "GRANTED_PRIVILEGES",
    "EFFECTIVE_PRIVILEGE_GRANTEES",
    "GRANTED_ROLES",
    "AUDIT_POLICIES",
    "AUDIT_TRAIL",
    "M_INIFILE_CONTENTS",
    "CONFIGURATION_PARAMETER_PROPERTIES",
]

KNOWLEDGE_BASE_DIR = PROJECT_ROOT / "data" / "knowledge_base"
SAMPLES_DIR = PROJECT_ROOT / "data" / "input" / "samples"

SLOT_DEFAULT_CONTROLS: dict[str, list[str]] = {
    "USERS": [
        "DB-AM-01_PLACEHOLDER",
        "DB-AM-02_PLACEHOLDER",
        "DB-AM-03_PLACEHOLDER",
        "DB-AM-04_PLACEHOLDER",
        "DB-PP-02_PLACEHOLDER",
        "DB-UAR-01_PLACEHOLDER",
        "DB-UAR-02_PLACEHOLDER",
    ],
    "M_PASSWORD_POLICY": ["DB-PP-01_PLACEHOLDER"],
    "GRANTED_PRIVILEGES": ["DB-UAR-02_PLACEHOLDER"],
    "EFFECTIVE_PRIVILEGE_GRANTEES": [
        "DB-PP-02_PLACEHOLDER",
        "DB-AM-02_PLACEHOLDER",
        "DB-UAR-01_PLACEHOLDER",
        "DB-AM-04_PLACEHOLDER",
        "DB-AM-05_PLACEHOLDER",
        "DB-AM-06_PLACEHOLDER",
    ],
    "GRANTED_ROLES": ["DB-UAR-01_PLACEHOLDER", "DB-AM-04_PLACEHOLDER"],
    "AUDIT_POLICIES": ["DB-AL-01_PLACEHOLDER"],
    "AUDIT_TRAIL": ["DB-AL-01_PLACEHOLDER"],
    "M_INIFILE_CONTENTS": ["DB-AL-01_PLACEHOLDER"],
    "CONFIGURATION_PARAMETER_PROPERTIES": [],
}
